// Generated by spider on 2021-06-30 11:30:42.304107

class AppVectoriaImages {
  AppVectoriaImages._();

  static const String appLogo = 'res/svg/app_logo.svg';
  static const String illEmpty = 'res/svg/ill_empty.svg';
}
