// Generated by spider on 2021-06-30 11:30:42.150294

class AppImages {
  AppImages._();

  static const String nutriscoreB = 'res/drawables/nutriscore_b.png';
  static const String nutriscoreA = 'res/drawables/nutriscore_a.png';
  static const String nutriscoreD = 'res/drawables/nutriscore_d.png';
  static const String nutriscoreC = 'res/drawables/nutriscore_c.png';
  static const String nutriscoreE = 'res/drawables/nutriscore_e.png';
}
